package com.techQuest.TechQuest.Domain.Enums;

public enum SkillType {
    ECONOMIC_POWER,
    SARCASM,
    PSYCHIC,
    POLYGLOT,
    MAGNIFICENT_ORATORY,
    CRITICAL_THINKING,
    PROBLEM_RESOLUTION,
    DECISION_MAKING,
    SUPER_STRENGTH,
    TELETRASNSPORT,
    INVISIBILITY,
    METAL_CONTROL
}
